INSERT INTO exercises (id, name, category, muscle_group, equipment, is_custom) VALUES
    (1,  'Barbell Squat',        'strength', 'quadriceps', 'barbell',    FALSE),
    (2,  'Bench Press',          'strength', 'chest',      'barbell',    FALSE),
    (3,  'Deadlift',             'strength', 'hamstrings', 'barbell',    FALSE),
    (4,  'Pull-up',              'strength', 'back',       'bodyweight', FALSE),
    (5,  'Overhead Press',       'strength', 'shoulders',  'barbell',    FALSE),
    (6,  'Barbell Row',          'strength', 'back',       'barbell',    FALSE),
    (7,  'Dumbbell Curl',        'strength', 'biceps',     'dumbbell',   FALSE),
    (8,  'Tricep Pushdown',      'strength', 'triceps',    'cable',      FALSE),
    (9,  'Leg Press',            'strength', 'quadriceps', 'machine',    FALSE),
    (10, 'Romanian Deadlift',    'strength', 'hamstrings', 'barbell',    FALSE),
    (11, 'Incline Bench Press',  'strength', 'chest',      'barbell',    FALSE),
    (12, 'Lat Pulldown',         'strength', 'back',       'cable',      FALSE),
    (13, 'Plank',                'strength', 'core',       'bodyweight', FALSE),
    (14, 'Running',              'cardio',   'full body',  'none',       FALSE),
    (15, 'Cycling',              'cardio',   'legs',       'bike',       FALSE),
    (16, 'Lunges',               'strength', 'quadriceps', 'bodyweight', FALSE),
    (17, 'Leg Curl',             'strength', 'hamstrings', 'machine',    FALSE),
    (18, 'Leg Extension',        'strength', 'quadriceps', 'machine',    FALSE),
    (19, 'Chest Fly',            'strength', 'chest',      'dumbbell',   FALSE),
    (20, 'Cable Fly',            'strength', 'chest',      'cable',      FALSE),
    (21, 'Face Pull',            'strength', 'shoulders',  'cable',      FALSE),
    (22, 'Lateral Raise',        'strength', 'shoulders',  'dumbbell',   FALSE),
    (23, 'Front Raise',          'strength', 'shoulders',  'dumbbell',   FALSE),
    (24, 'Hammer Curl',          'strength', 'biceps',     'dumbbell',   FALSE),
    (25, 'Preacher Curl',        'strength', 'biceps',     'machine',    FALSE),
    (26, 'Skull Crushers',       'strength', 'triceps',    'barbell',    FALSE),
    (27, 'Dips',                 'strength', 'triceps',    'bodyweight', FALSE),
    (28, 'Seated Row',           'strength', 'back',       'machine',    FALSE),
    (29, 'T-Bar Row',            'strength', 'back',       'barbell',    FALSE),
    (30, 'Crunches',             'strength', 'core',       'bodyweight', FALSE),
    (31, 'Hanging Leg Raise',    'strength', 'core',       'bodyweight', FALSE),
    (32, 'Mountain Climbers',    'cardio',   'core',       'bodyweight', FALSE),
    (33, 'Jump Rope',            'cardio',   'full body',  'rope',       FALSE),
    (34, 'Rowing',               'cardio',   'full body',  'machine',    FALSE),
    (35, 'Elliptical',           'cardio',   'full body',  'machine',    FALSE);